port-labs/terraform-provider-port-labs

.gitignore
port/cli/blueprint.go
port/cli/client.go
port/cli/entity.go
port/cli/permission.go
port/cli/relation.go
port/resource_port_entity.go

As part of routes matuarity of Port.i, this PR adjusts the terraform provider to support V1 routes in Port.
Query string
exclude_mirror_properties -> exclude_calculated_properties
Routes changed to v1 instead of v0.1 
Identifier changed to be scoped by blueprint instead of global identifier
Changed to use v1 rotues

Added support for new V1 routes

---

docs/resources/action.md
docs/resources/blueprint.md
port/cli/models.go
port/resource_port_action.go
port/resource_port_action_test.go
port/resource_port_blueprint.go
port/resource_port_blueprint_test.go

Add support for multiple types (including `array`) of default of a Blueprint property and Action user property.

Port 1843 terraform provider support multiple types of default of a property

---

port/action/resource_test.go
port/action/schema.go

Replace the older (and deprecated by port) fernet encryption algorithm with the newly supported aes256-gcm.

PORT-5213-replace-fernet-with-aes256-gcm-in-terraform

---

docs/resources/port_action.md
docs/resources/port_action_permissions.md
docs/resources/port_aggregation_properties.md
docs/resources/port_blueprint.md
docs/resources/port_entity.md
docs/resources/port_scorecard.md
docs/resources/port_team.md
docs/resources/port_webhook.md
internal/cli/blueprint.go
internal/cli/migrations.go
internal/cli/models.go
internal/consts/migrations.go
port/blueprint/model.go
port/blueprint/resource.go
port/blueprint/resource_test.go
port/blueprint/schema.go
port/scorecard/schema.go

Fixes - #61 
What - Added support to force delete blueprints
Why - If terraform only manages the blueprint, but entities are ingested from different sources, the destroying of the blueprint will fail as there are entities left in the blueprint.
How - Introduced a new flag to indicate whether to delete the blueprint `PORT_FORCE_DELETE_ENTITIES=true`

Support Force delete blueprint

---

port/action-permissions/resource.go
port/action-permissions/resource_test.go
port/action-permissions/schema.go

What - Changed the properties to required 
Why - As they are already required from the backend, the backend doesn't support `null` but rather an empty list `[]` so aligning the tf behavior to terraform
How -

Action Permissions - Fix fields to required

---

Makefile
docs/resources/port_page.md
examples/resources/port_page/main.tf
internal/cli/models.go
port/page/model.go
port/page/pageToPortBody.go
port/page/refreshPageToState.go
port/page/resource.go
port/page/resource_test.go
port/page/schema.go

- **Add description to page resource**
- **Allow override for running tests**
What - Add the missing `description` property for pages

Add description to the page component

---

docs/resources/port_action.md
docs/resources/port_action_permissions.md
docs/resources/port_aggregation_properties.md
docs/resources/port_blueprint.md
docs/resources/port_blueprint_permissions.md
docs/resources/port_entity.md
docs/resources/port_page_permissions.md
docs/resources/port_scorecard.md
docs/resources/port_team.md
docs/resources/port_webhook.md
port/action/schema.go
port/blueprint-permissions/schema.go

Update action and blueprints permissions documentation

---

port/entity/model.go
port/entity/refreshEntityToState.go
port/entity/resource_test.go

What - Support null relation in single_relation in entities. (it is already supported in many_relations)
Why - Terraform support null values when wanting to send empty attributes. Port can configure relations as non-required. there was no support for a case when an entity didn't have a relation that was defined in the blueprint as non-required.
How - changed the model.go to support string and null (using *)

fix: bug terraform cannot create entity without a relation even though the relation is not required

---

docs/resources/port_blueprint.md
internal/cli/blueprint.go
port/blueprint/model.go
port/blueprint/resource.go
port/blueprint/resource_test.go
port/blueprint/schema.go

What - Currently by default we create catalog page for any blueprint creation, for use cases such as maintaining all the blueprints and pages through IaC.
Why - this can cause state discrepancies and therefor we want to add option skip that on creation
How - introduced `create_catalog_page` flag to blueprint resource

Add option to not create catalog page on blueprint creation

---

docs/resources/port_action.md
docs/resources/port_integration.md
docs/resources/port_page.md
port/integration/refreshIntegrationToState.go
port/integration/resource.go
port/integration/resource_test.go
port/integration/schema.go
port/page/schema.go

For webhooks/integrations, if no change destination as defined when
creating the integration, it now returns a change destination with an
empty string as url as oppose to no change destination
What - Update integrations port body parser
Why - Since the schema was changed, which wasn't defined to

Compatibility with new default empty url in schema

---

docs/resources/port_integration.md
docs/resources/port_page.md
examples/provider.tf
port/integration/schema.go
port/page/schema.go

What - Small docs change - fix wording and add import-state how to link

Update docs with link to import-state how-to

---

docs/resources/port_scorecard.md
internal/cli/models.go
port/scorecard/model.go
port/scorecard/refreshScorecardState.go
port/scorecard/resource.go
port/scorecard/schema.go
port/scorecard/scorecardResourceToPortBody.go

What - Added levels to scorecards
Why - To enable custom management of the scorecard levels
How - Add to schema + add state handling to where levels is provided by the terraform resource or not 

Add custom scorecard levels

---

port/page-permissions/model.go
port/page-permissions/refreshPagePermissionsToState.go
port/page-permissions/resource_test.go

What - Fix page permissions import
Why - Import didn't work due to wrong initialization of the model object
How - Changed reference to a pointer to allow passing null when using import
Fixes the following 
```
➜  import-action terraform plan -generate-config-out page-permission-state.tf
port_page_permissions.gitlabIssues: Preparing import... [id=gitlabIssues]
port_page_permissions.gitlabIssues: Refreshing state... [id=gitlabIssues]
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: Value Conversion Error
│
│ An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the
│ following to the provider developer:
│
│ Received null value, however the target type cannot handle null values. Use the …
```

Fix page permissions import

---

port/action/actionStateToPortBody.go
port/action/refreshActionState.go
port/action/resource_test.go
port/action/schema.go

What - Fix upsert entity invocation
Why - Cannot use it without identifier
How - mark identifier optional and fix access to it

Fix upsert entity invocation

---

docs/data-sources/port_search.md
docs/resources/port_action.md
docs/resources/port_action_permissions.md
docs/resources/port_aggregation_properties.md
docs/resources/port_blueprint.md
docs/resources/port_blueprint_permissions.md
docs/resources/port_entity.md
docs/resources/port_integration.md
docs/resources/port_page.md
docs/resources/port_page_permissions.md
docs/resources/port_scorecard.md
docs/resources/port_team.md
docs/resources/port_webhook.md
internal/cli/models.go
internal/utils/utils.go
port/action/actionStateToPortBody.go
port/action/model.go
port/action/refreshActionState.go
port/action/resource_test.go
port/action/schema.go

What - Fix required approval to support ANY and ALL
Why - Support new API for actions
How - Change required_approval schema from boolean to string and allow "true", "false", "ANY", "ALL"

Port 9649 bug terraform does not support multiple approvals

---

README.md

What - Link to the Port documentation about Terraform integration.
Why - The link in the README file is broken.
How - The link is updated to point to the proper location.

Fix link to Port documentation

---

examples/resources/port_action/main.tf
internal/cli/models.go
internal/consts/provider.go
port/action/actionStateToPortBody.go
port/action/model.go
port/action/refreshActionState.go
port/action/resource_test.go
port/action/schema.go

What - Add support for the upcoming "run updated" automation event type
How - Added the relevant models and schemas to support creating such an action

Add automations run updated event trigger support

---

docs/resources/port_integration.md
examples/resources/port_integration/main.tf
port/integration/schema.go

What - When altering an integrations version outside of terraform, it would affect the state even if not specified in a `port_integration` section
Why - Allows updating versions of integrations outside of terraform, keep terraform for updating configuration and mappings
How - Make `version` both optionable and computed

Ensure that `version` is not part of the state if not explicitly in the tf file

---

docs/resources/port_action.md
examples/resources/port_action/main.tf
internal/cli/models.go
port/action/array.go
port/action/model.go
port/action/resource_test.go
port/action/schema.go
port/action/string.go

What - added sort to self service actions user inputs
Why - to enable entities selection sort in the UI
How - added sort to relevant models

Add sort to action user inputs

---

docs/resources/port_integration.md
port/integration/schema.go

What - replace the link to mapping on documentation to import existing integrations and manage their mappings
Why - Link was broken as guides have been moved
How - Restructuring in documentation service

Fixed broken link in port integration documentation

---

docs/resources/port_action.md
internal/cli/models.go
port/action/actionStateToPortBody.go
port/action/model.go
port/action/refreshActionState.go
port/action/resource_test.go
port/action/schema.go

What - add support for the new action step definition feature
How - added the relevant models and schemas + tests

PORT-8983-form-inputs-sections-steps-for-actions

---

Makefile
port/action/resource_test.go
port/blueprint/readStateToPortBody.go
port/blueprint/resource_test.go

https://getport.atlassian.net/browse/PORT-10617?atlOrigin=eyJpIjoiYTIyNDdiMWFlZjhkNDVkMTk5NmFhYzFhNDg2MzQ4ZTYiLCJwIjoiaiJ9
fix the colors mapping to blueprint in calculation property

fix the colors mapping to blueprint in calculation property

---

docs/resources/port_scorecard.md
internal/cli/models.go
port/scorecard/model.go
port/scorecard/refreshScorecardState.go
port/scorecard/resource_test.go
port/scorecard/schema.go
port/scorecard/scorecardResourceToPortBody.go

This PR implements support for Filters object on the scorecard resource.
It includes implementation, tests and documentation update with a matching example.

Scorecard filter support

---

port/blueprint/readStateToPortBody.go

Calculation properties icons were checked against the state rather than the property itself. This caused icons to not be applied if the blueprint itself had no icon.

Calculation property icons mishandle

---

port/action/isTrueValidator.go
port/action/resource_test.go
port/action/schema.go

What - i've added validation that checks that the required value is only true and not false
Why - cause some users have used false and it cause them to have problems in re applying the actions. it creates drifts
How - ive added validations that checks if it is only true

add validation that required won't be false

---

port/entity/refreshEntityToState.go

What - Update the state when refreshing the entity relations
Why - Because otherwise nothing gets updated.
How - by referencing the state struct.

PORT-13253: Update the state when refreshing the entity relations.

---

docs/resources/port_entity.md
port/entity/schema.go

What - Change port_entity title attribute from optional to required
Why - The title is required in the server, and if it is missing it causes weird
warnings during plan.

Change port_entity title attribute from optional to required

---

port/action/refreshActionState.go

What - Add a nil check during port_action buildUserProperties
Why - When running terraform plan with import statements, the
SelfServiceTrigger is nil.

Add a nil check during port_action buildUserProperties

---

.github/workflows/ci.yml

What - Upload test report even after failures
Why - failed tests didn't have their reports
How - added an `if: always()` to the `actions/upload-artifact` step.

Upload test report even after failures

---

.github/workflows/ci.yml
docs/index.md
go.mod
go.sum
internal/acctest/acctest.go
internal/cli/client.go
internal/cli/models.go
internal/utils/utils.go
internal/utils/utils_test.go
port/action/array.go
port/action/refreshActionState.go
port/action/resource.go
port/aggregation-properties/refreshAggregationPropertyToState.go
port/aggregation-properties/resource.go
port/integration/refreshIntegrationToState.go
port/integration/resource.go
port/scorecard/refreshScorecardState.go
port/scorecard/resource.go
port/scorecard/resource_test.go
provider/provider.go

What - Allow to disable the auto JSON HTML escaping
Why - To support clients that don't use Terraform directly and are hurt by the forced encoding issue.
How - Used the `json.Encoder` structure and passed a global json_escape_html in the provider block.

Allow to disable the auto JSON HTML escaping

---

port/action-permissions/refreshActionPermissionsToState.go
port/action-permissions/resource.go
port/action/array.go
port/action/refreshActionState.go
port/blueprint/array.go
port/blueprint/resource.go
port/blueprint/updatePropertiesToState.go
port/entity/refreshEntityToState.go
port/entity/resource.go
port/page/refreshPageToState.go
port/page/resource.go
port/search/dataSource.go
port/search/searchResultToState.go
port/system_blueprint/resource.go
port/system_blueprint/updatePropertiesToState.go

What -Replace all json.Marshal calls with utils.GoObjectToTerraformString
Why - To make sure everything uses the same jsonEscapeHTML flag
How -

Replace all json.Marshal calls with utils.GoObjectToTerraformString

---

docs/resources/port_action.md
examples/resources/port_action/pattern_jq_query/README.md
examples/resources/port_action/pattern_jq_query/main.tf
internal/cli/models.go
port/action/model.go
port/action/resource_test.go
port/action/schema.go
port/action/string.go

Verify CI for https://github.com/port-labs/terraform-provider-port-labs/pull/224
- Update schema to support the new parameter: pattern_jq_query
- Update documentation with examples of both usage patterns
- Add comprehensive tests for all use cases
- Adjust existing pattern validation to prevent conflicts
Description
What - Added support for dynamic pattern validation using JQ queries for string properties. The pattern_jq_query parameter allows users to specify validation rules that change based on context.
Why - This enhancement enables more flexible validation rules that can adapt to different situations without requiring multiple actions or complex conditional logic
How - Implemented by:
Adding the pattern_jq_query field to the schema with conflict validation against pattern
Modifying …

verify contribution from hedinasr

---

docs/resources/port_action.md
internal/cli/models.go
port/action/model.go
port/action/resource_test.go
port/action/schema.go
port/action/string.go

What - Add `pattern_jq_query` parameter to `self_service_trigger.user_properties.string_props`
Why - Because this is a missing parameter
How - Implemented the above, and added test to confirm

add pattern_jq_query parameter to string_props

---

.github/workflows/ci.yml
.github/workflows/docs-check.yml
README.md
go.mod
internal/utils/slices.go
port/action-permissions/refreshActionPermissionsToState.go
port/blueprint-permissions/refreshBluePrintPermissionsToState.go
port/page-permissions/refreshPagePermissionsToState.go

What - When refreshing permission lists, use the ordering of values from the previous state for sorting values from the server
Why - To keep the sort that exists in the state instead of forcing an arbitrary sorting from the server.
How - Transform the old lists to a mapping from their string values to their index in the slice. Then use SortedFunc to sort the values according to their positioning.

Sort permission lists as the last state

---

internal/cli/models.go

What - add dynamic unknown fields to the blueprint property types
Why - to successfully import object properties, especially the 'filter' object property of SCAB feature
How - Add custom json marshal and unmarshal to the blueprint property strucure

add dynamic unknown fields to the blueprint property types

---

.gitignore
docs/resources/port_page.md
examples/resources/port_page/main.tf
port/page/resource_test.go
port/page/schema.go

> [!WARNING]
> To be merged on the 22nd of June as part of the migration for filters UI.
What - add the `blueprint` prop to relevant widgets (see https://github.com/port-labs/Port/pull/7374)
Why -
How -

PORT-14153 feat: add blueprint to widget example
