port-labs/terraform-provider-port-labs

- .github/PULL_REQUEST_TEMPLATE.md
Add PR template description for future PRs
> port-5964 Add Pull Request Template

- port/blueprint/readStateToPortBody.go
- port/blueprint/resource_test.go
- port/blueprint/updatePropertiesToState.go
What - Fix icon in calculation property
> Fix icon in calculation property

- docs/resources/port_aggregation_properties.md
- port/aggregation-properties/schema.go
What - change from aggregation property to aggregation properties
Why -
How -
> update docs for aggregation properties

- port/action/resource_test.go
- port/action/schema.go
What - fix webhook approval format and add tests. Fixes #101 
> fix webhook approval format and add tests

- port/action/array.go
- port/action/boolean.go
- port/action/model.go
- port/action/number.go
- port/action/object.go
- port/action/refreshActionState.go
- port/action/resource_test.go
- port/action/schema.go
- port/action/string.go
> added support for array dataset

- README.md
> change logo in README

- README.md
What - change logo in README (again)
> change logo in README (again)

- port/action-permissions/resource.go
- port/blueprint-permissions/resource.go
- port/page-permissions/resource.go
What - Ensure that resources are removed from the state if the resource doesn't exist
> Remove resource from state when resource doesn't exist

- docs/resources/port_action.md
- internal/cli/models.go
- internal/utils/utils.go
- port/action/actionStateToPortBody.go
- port/action/model.go
- port/action/refreshActionState.go
- port/action/resource_test.go
- port/action/schema.go
What - Self service conditional trigger
Why - New option in the API support
How - Adding a JSON field condition to the terraform provider
> feat: added condition for self_service trigger

- .github/workflows/cd.yml
fixes - https://goreleaser.com/deprecations/#-rm-dist, instead of using `--rm-dist` to use `--clean`
What -
Why -
How -
> [CI] Upgrade goreleaser version and fix deprecated methods

- .goreleaser.yml
> Bump `goreleaser.yaml` to version 2 and change deprecated variables 

- port/action/actionStateToPortBody.go
- port/action/model.go
- port/action/refreshActionState.go
- port/action/resource_test.go
- port/action/schema.go
What - add support for team jq
Why - user asked for jq in team property
How - add the new teamjq property in the upsert entity mapping
> add teams_jq support

- docs/resources/port_scorecard.md
- internal/cli/models.go
- port/scorecard/model.go
- port/scorecard/refreshScorecardState.go
- port/scorecard/resource_test.go
- port/scorecard/schema.go
- port/scorecard/scorecardResourceToPortBody.go
Add support for scorecard rule description
> added rule description support:

- .github/workflows/ci.yml
- .golangci.yml
- Makefile
- internal/cli/search.go
- port/blueprint/resource.go
Ensure deletion of ownership state when missing in Port
> Delete ownership when removed from port

- .github/workflows/ci.yml
- docs/resources/port_entity.md
- port/action/refreshActionState.go
- port/entity/refreshEntityToState.go
- port/entity/schema.go
What - Remove redundant sort
Why - It is not needed
How -
> refreshRelationsEntityState: remove redundant sort

- port/blueprint/resource.go
- port/blueprint/resource_test.go
What - Properly write ownership title to state
Why - This is supported by the provider, but missing some functionality
How - add the missing functionality to write to state
> write ownership title to state

- .gitignore
- CONTRIBUTING.md
- README.md
- devbox.json
- devbox.lock
What - devbox is a dev env as code tool
Why - devbox allows us quickly onboard new
contributers and makes sure we all use the same tools in the same versions.
We use this in our monorepo as well.
How - see CONTRIBUTING.md on how to set this up
https://www.jetify.com/devbox
> chore: devbox for managing dev env

- internal/cli/models.go
What - Use reflection to get the known fields
Why - to avoid maintaining two lists of known fields
> Port 14830 bug bug in scab terraform

- docs/resources/port_action.md
- examples/resources/port_action/main.tf
- internal/cli/models.go
- port/action/actionStateToPortBody.go
- port/action/model.go
- port/action/refreshActionState.go
- port/action/resource_test.go
- port/action/schema.go
What - add support to action title in the terraform provider
Why - cause it is a new feature supported in the backend so need to be supported in the tf provider to
How - via code
> add support for action titles in action resource

- port/page/resource.go
What - fixed missing date data in UpdatePage payload
Why - error when running update page
How - added call to GetPage after UpdatePage
> added get page after page update to add missing date context
